eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
server:
  port: 8088
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: scStu
    password: yGTaykiSwr
    url: jdbc:mysql://47.107.44.224:3306/scStu?characterEncoding=utf-8$useSSL=false
  jpa:
    show-sql: true