version: '3'
services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  admin:
    image: chenchuxin/dubbo-admin
    depends_on:
      - zookeeper
    ports:
      - 8080:8080
    environment:
      - dubbo.registry.address=zookeeper://zookeeper:2181
      - dubbo.admin.root.password=root
      - dubbo.admin.guest.password=guest